name: User Service CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push user-service image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ttrpg-be-user-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_PRIVATE_KEY }}
        script: |
          cd ~/projects/ttrpg_app/backend/user-service
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ttrpg-be-user-service:latest
          cd ../..
          docker compose up -d user-service
